# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-02 07:03
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='hui'),
        ),
    ]
